module Evergreen.Migrate.V11 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V11.Types
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V9.Types.FrontendModel -> ModelMigration Evergreen.V11.Types.FrontendModel Evergreen.V11.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V9.Types.BackendModel -> ModelMigration Evergreen.V11.Types.BackendModel Evergreen.V11.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V9.Types.FrontendMsg -> MsgMigration Evergreen.V11.Types.FrontendMsg Evergreen.V11.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V9.Types.ToBackend -> MsgMigration Evergreen.V11.Types.ToBackend Evergreen.V11.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V9.Types.BackendMsg -> MsgMigration Evergreen.V11.Types.BackendMsg Evergreen.V11.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V9.Types.ToFrontend -> MsgMigration Evergreen.V11.Types.ToFrontend Evergreen.V11.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V9.Types.BackendModel -> Evergreen.V11.Types.BackendModel
migrate_Types_BackendModel old =
    { teams = old.teams |> Dict.map (\k -> migrate_Types_TeamData)
    , nextId = old.nextId
    , randomSeed = old.randomSeed
    , teamSessions = old.teamSessions
    }


migrate_Types_FrontendModel : Evergreen.V9.Types.FrontendModel -> Evergreen.V11.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , currentTeam = old.currentTeam
    , activeMemberId = old.activeMemberId
    , createTeamForm = old.createTeamForm |> migrate_Types_CreateTeamForm
    , createMatchForm = old.createMatchForm |> migrate_Types_CreateMatchForm
    , createMemberForm = old.createMemberForm |> migrate_Types_CreateMemberForm
    , matches = old.matches |> List.map migrate_Types_Match
    , members = old.members
    , availability = old.availability |> List.map migrate_Types_AvailabilityRecord
    , showCreateMatchModal = old.showCreateMatchModal
    , showCreateMemberModal = old.showCreateMemberModal
    , showMemberSelectionModal = old.showMemberSelectionModal
    , showCreateMemberInModal = old.showCreateMemberInModal
    , showChangeMatchDateModal = old.showChangeMatchDateModal
    , changeMatchDateForm = old.changeMatchDateForm
    , changeMatchDateMatchId = old.changeMatchDateMatchId
    , showShareModal = old.showShareModal
    , showImportIcsModal = old.showImportIcsModal
    , showAddMatchDropdown = old.showAddMatchDropdown
    , icsImportUrl = old.icsImportUrl
    , icsImportStatus = old.icsImportStatus
    , parsedIcsMatches = old.parsedIcsMatches
    , allParsedIcsMatches = old.allParsedIcsMatches
    , icsImportSelectedMatches = old.icsImportSelectedMatches
    , expandedMatches = old.expandedMatches
    , expandedPredictions = old.expandedPredictions
    , pastMatchesShown = old.pastMatchesShown
    , pastMatchesExpanded = old.pastMatchesExpanded
    , hostname = old.hostname
    , currentDate = old.currentDate
    , confirmedTeamCodes = old.confirmedTeamCodes
    , accessCodeRequired = old.accessCodeRequired
    , enteredAccessCode = old.enteredAccessCode
    , datePredictions = old.datePredictions |> Dict.map (\k -> Dict.map (\l -> Dict.map (\m -> migrate_Types_DatePrediction)))
    , showDatePredictionModal = old.showDatePredictionModal
    , datePredictionMatchId = old.datePredictionMatchId
    , datePredictionForm = old.datePredictionForm
    , reservePlayers = Dict.empty
    , showAddReservePlayerModal = False
    , addReservePlayerMatchId = Nothing
    , addReservePlayerForm = ""
    }


migrate_Types_Availability : Evergreen.V9.Types.Availability -> Evergreen.V11.Types.Availability
migrate_Types_Availability old =
    case old of
        Evergreen.V9.Types.Available ->
            Evergreen.V11.Types.Available

        Evergreen.V9.Types.NotAvailable ->
            Evergreen.V11.Types.NotAvailable

        Evergreen.V9.Types.Maybe ->
            Evergreen.V11.Types.Maybe


migrate_Types_AvailabilityRecord : Evergreen.V9.Types.AvailabilityRecord -> Evergreen.V11.Types.AvailabilityRecord
migrate_Types_AvailabilityRecord old =
    { memberId = old.memberId
    , matchId = old.matchId
    , availability = old.availability |> migrate_Types_Availability
    }


migrate_Types_CreateMatchForm : Evergreen.V9.Types.CreateMatchForm -> Evergreen.V11.Types.CreateMatchForm
migrate_Types_CreateMatchForm old =
    old


migrate_Types_CreateMemberForm : Evergreen.V9.Types.CreateMemberForm -> Evergreen.V11.Types.CreateMemberForm
migrate_Types_CreateMemberForm old =
    old


migrate_Types_CreateTeamForm : Evergreen.V9.Types.CreateTeamForm -> Evergreen.V11.Types.CreateTeamForm
migrate_Types_CreateTeamForm old =
    old


migrate_Types_DatePrediction : Evergreen.V9.Types.DatePrediction -> Evergreen.V11.Types.DatePrediction
migrate_Types_DatePrediction old =
    { predictedDate = old.predictedDate
    , memberId = old.memberId
    , availability = old.availability |> migrate_Types_Availability
    }


migrate_Types_FrontendMsg : Evergreen.V9.Types.FrontendMsg -> Evergreen.V11.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V9.Types.UrlClicked p0 ->
            Evergreen.V11.Types.UrlClicked p0

        Evergreen.V9.Types.UrlChanged p0 ->
            Evergreen.V11.Types.UrlChanged p0

        Evergreen.V9.Types.CreateTeamFormUpdated p0 ->
            Evergreen.V11.Types.CreateTeamFormUpdated (p0 |> migrate_Types_CreateTeamForm)

        Evergreen.V9.Types.CreateTeamSubmitted ->
            Evergreen.V11.Types.CreateTeamSubmitted

        Evergreen.V9.Types.CreateMatchFormUpdated p0 ->
            Evergreen.V11.Types.CreateMatchFormUpdated (p0 |> migrate_Types_CreateMatchForm)

        Evergreen.V9.Types.CreateMatchSubmitted p0 ->
            Evergreen.V11.Types.CreateMatchSubmitted p0

        Evergreen.V9.Types.ShowCreateMatchModal ->
            Evergreen.V11.Types.ShowCreateMatchModal

        Evergreen.V9.Types.HideCreateMatchModal ->
            Evergreen.V11.Types.HideCreateMatchModal

        Evergreen.V9.Types.CreateMemberFormUpdated p0 ->
            Evergreen.V11.Types.CreateMemberFormUpdated (p0 |> migrate_Types_CreateMemberForm)

        Evergreen.V9.Types.CreateMemberSubmitted p0 ->
            Evergreen.V11.Types.CreateMemberSubmitted p0

        Evergreen.V9.Types.ShowCreateMemberModal ->
            Evergreen.V11.Types.ShowCreateMemberModal

        Evergreen.V9.Types.HideCreateMemberModal ->
            Evergreen.V11.Types.HideCreateMemberModal

        Evergreen.V9.Types.ShowMemberSelectionModal ->
            Evergreen.V11.Types.ShowMemberSelectionModal

        Evergreen.V9.Types.HideMemberSelectionModal ->
            Evergreen.V11.Types.HideMemberSelectionModal

        Evergreen.V9.Types.SelectActiveMember p0 ->
            Evergreen.V11.Types.SelectActiveMember p0

        Evergreen.V9.Types.ShowCreateMemberInModal ->
            Evergreen.V11.Types.ShowCreateMemberInModal

        Evergreen.V9.Types.HideCreateMemberInModal ->
            Evergreen.V11.Types.HideCreateMemberInModal

        Evergreen.V9.Types.LocalStorageMessage p0 ->
            Evergreen.V11.Types.LocalStorageMessage p0

        Evergreen.V9.Types.UpdateCurrentDate ->
            Evergreen.V11.Types.UpdateCurrentDate

        Evergreen.V9.Types.LogoutRequested ->
            Evergreen.V11.Types.LogoutRequested

        Evergreen.V9.Types.SetAvailability p0 p1 p2 ->
            Evergreen.V11.Types.SetAvailability p0 p1 (p2 |> migrate_Types_Availability)

        Evergreen.V9.Types.ToggleMatchDetails p0 ->
            Evergreen.V11.Types.ToggleMatchDetails p0

        Evergreen.V9.Types.TogglePredictionDetails p0 p1 ->
            Evergreen.V11.Types.TogglePredictionDetails p0 p1

        Evergreen.V9.Types.LoadMorePastMatches ->
            Evergreen.V11.Types.LoadMorePastMatches

        Evergreen.V9.Types.TogglePastMatchesSection ->
            Evergreen.V11.Types.TogglePastMatchesSection

        Evergreen.V9.Types.ShowChangeMatchDateModal p0 ->
            Evergreen.V11.Types.ShowChangeMatchDateModal p0

        Evergreen.V9.Types.HideChangeMatchDateModal ->
            Evergreen.V11.Types.HideChangeMatchDateModal

        Evergreen.V9.Types.ChangeMatchDateFormUpdated p0 p1 ->
            Evergreen.V11.Types.ChangeMatchDateFormUpdated p0 p1

        Evergreen.V9.Types.ChangeMatchDateSubmitted p0 p1 ->
            Evergreen.V11.Types.ChangeMatchDateSubmitted p0 p1

        Evergreen.V9.Types.ShowShareModal ->
            Evergreen.V11.Types.ShowShareModal

        Evergreen.V9.Types.HideShareModal ->
            Evergreen.V11.Types.HideShareModal

        Evergreen.V9.Types.SubmitAccessCodeRequested p0 p1 ->
            Evergreen.V11.Types.SubmitAccessCodeRequested p0 p1

        Evergreen.V9.Types.AccessCodeInputChanged p0 p1 ->
            Evergreen.V11.Types.AccessCodeInputChanged p0 p1

        Evergreen.V9.Types.GetAccessCode p0 ->
            Evergreen.V11.Types.GetAccessCode p0

        Evergreen.V9.Types.AccessCodeLoaded p0 p1 ->
            Evergreen.V11.Types.AccessCodeLoaded p0 p1

        Evergreen.V9.Types.CopyToClipboard p0 ->
            Evergreen.V11.Types.CopyToClipboard p0

        Evergreen.V9.Types.ShowImportIcsModal ->
            Evergreen.V11.Types.ShowImportIcsModal

        Evergreen.V9.Types.HideImportIcsModal ->
            Evergreen.V11.Types.HideImportIcsModal

        Evergreen.V9.Types.ToggleAddMatchDropdown ->
            Evergreen.V11.Types.ToggleAddMatchDropdown

        Evergreen.V9.Types.IcsFileSelectButtonClicked ->
            Evergreen.V11.Types.IcsFileSelectButtonClicked

        Evergreen.V9.Types.IcsFileSelected p0 ->
            Evergreen.V11.Types.IcsFileSelected p0

        Evergreen.V9.Types.IcsFileContentRead p0 ->
            Evergreen.V11.Types.IcsFileContentRead p0

        Evergreen.V9.Types.IcsImportMatchToggled p0 p1 ->
            Evergreen.V11.Types.IcsImportMatchToggled p0 p1

        Evergreen.V9.Types.ConfirmImportIcs p0 ->
            Evergreen.V11.Types.ConfirmImportIcs p0

        Evergreen.V9.Types.ShowDatePredictionModal p0 ->
            Evergreen.V11.Types.ShowDatePredictionModal p0

        Evergreen.V9.Types.HideDatePredictionModal ->
            Evergreen.V11.Types.HideDatePredictionModal

        Evergreen.V9.Types.DatePredictionFormUpdated p0 ->
            Evergreen.V11.Types.DatePredictionFormUpdated p0

        Evergreen.V9.Types.AddDatePrediction p0 p1 ->
            Evergreen.V11.Types.AddDatePrediction p0 p1

        Evergreen.V9.Types.RemoveDatePrediction p0 ->
            Evergreen.V11.Types.RemoveDatePrediction p0

        Evergreen.V9.Types.UpdatePredictionAvailability p0 p1 p2 ->
            Evergreen.V11.Types.UpdatePredictionAvailability p0 p1 (p2 |> migrate_Types_Availability)

        Evergreen.V9.Types.ChoosePredictedDate p0 p1 ->
            Evergreen.V11.Types.ChoosePredictedDate p0 p1

        Evergreen.V9.Types.NoOpFrontendMsg ->
            Evergreen.V11.Types.NoOpFrontendMsg


migrate_Types_Match : Evergreen.V9.Types.Match -> Evergreen.V11.Types.Match
migrate_Types_Match old =
    { id = old.id
    , opponent = old.opponent
    , date = old.date
    , time = old.time
    , isHome = old.isHome
    , venue = old.venue
    , season = old.season
    , seasonHalf = old.seasonHalf |> migrate_Types_SeasonHalf
    , matchday = old.matchday
    , originalDate = old.originalDate
    }


migrate_Types_Member : Evergreen.V9.Types.Member -> Evergreen.V11.Types.Member
migrate_Types_Member old =
    old


migrate_Types_Page : Evergreen.V9.Types.Page -> Evergreen.V11.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V9.Types.HomePage ->
            Evergreen.V11.Types.HomePage

        Evergreen.V9.Types.CreateTeamPage ->
            Evergreen.V11.Types.CreateTeamPage

        Evergreen.V9.Types.TeamPage p0 ->
            Evergreen.V11.Types.TeamPage p0

        Evergreen.V9.Types.NotFoundPage ->
            Evergreen.V11.Types.NotFoundPage


migrate_Types_SeasonData : Evergreen.V9.Types.SeasonData -> Evergreen.V11.Types.SeasonData
migrate_Types_SeasonData old =
    { hinrunde = old.hinrunde |> List.map migrate_Types_Match
    , rückrunde = old.rückrunde |> List.map migrate_Types_Match
    }


migrate_Types_SeasonHalf : Evergreen.V9.Types.SeasonHalf -> Evergreen.V11.Types.SeasonHalf
migrate_Types_SeasonHalf old =
    case old of
        Evergreen.V9.Types.Hinrunde ->
            Evergreen.V11.Types.Hinrunde

        Evergreen.V9.Types.Rückrunde ->
            Evergreen.V11.Types.Rückrunde


migrate_Types_Team : Evergreen.V9.Types.Team -> Evergreen.V11.Types.Team
migrate_Types_Team old =
    old


migrate_Types_TeamData : Evergreen.V9.Types.TeamData -> Evergreen.V11.Types.TeamData
migrate_Types_TeamData old =
    { team = old.team |> migrate_Types_Team
    , seasons = old.seasons |> Dict.map (\k -> migrate_Types_SeasonData)
    , members = old.members
    , availability = old.availability |> Dict.map (\k -> Dict.map (\l -> migrate_Types_Availability))
    , datePredictions = old.datePredictions |> Dict.map (\k -> Dict.map (\l -> Dict.map (\m -> migrate_Types_DatePrediction)))
    , reservePlayers = Dict.empty
    }


migrate_Types_ToBackend : Evergreen.V9.Types.ToBackend -> Evergreen.V11.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V9.Types.CreateTeamRequest p0 p1 p2 p3 p4 ->
            Evergreen.V11.Types.CreateTeamRequest p0 p1 p2 p3 p4

        Evergreen.V9.Types.GetTeamRequest p0 p1 ->
            Evergreen.V11.Types.GetTeamRequest p0 p1

        Evergreen.V9.Types.SubmitAccessCode p0 p1 ->
            Evergreen.V11.Types.SubmitAccessCode p0 p1

        Evergreen.V9.Types.CreateMatchRequest p0 p1 p2 ->
            Evergreen.V11.Types.CreateMatchRequest p0 (p1 |> migrate_Types_CreateMatchForm) p2

        Evergreen.V9.Types.CreateMemberRequest p0 p1 p2 ->
            Evergreen.V11.Types.CreateMemberRequest p0 (p1 |> migrate_Types_CreateMemberForm) p2

        Evergreen.V9.Types.UpdateAvailabilityRequest p0 p1 p2 p3 ->
            Evergreen.V11.Types.UpdateAvailabilityRequest p0 p1 (p2 |> migrate_Types_Availability) p3

        Evergreen.V9.Types.ChangeMatchDateRequest p0 p1 p2 p3 ->
            Evergreen.V11.Types.ChangeMatchDateRequest p0 p1 p2 p3

        Evergreen.V9.Types.AddDatePredictionRequest p0 p1 p2 p3 ->
            Evergreen.V11.Types.AddDatePredictionRequest p0 p1 p2 p3

        Evergreen.V9.Types.UpdatePredictionAvailabilityRequest p0 p1 p2 p3 p4 ->
            Evergreen.V11.Types.UpdatePredictionAvailabilityRequest p0 p1 p2 (p3 |> migrate_Types_Availability) p4

        Evergreen.V9.Types.RemoveDatePredictionRequest p0 p1 p2 ->
            Evergreen.V11.Types.RemoveDatePredictionRequest p0 p1 p2

        Evergreen.V9.Types.ChoosePredictedDateRequest p0 p1 p2 p3 ->
            Evergreen.V11.Types.ChoosePredictedDateRequest p0 p1 p2 p3

        Evergreen.V9.Types.NoOpToBackend ->
            Evergreen.V11.Types.NoOpToBackend


migrate_Types_ToFrontend : Evergreen.V9.Types.ToFrontend -> Evergreen.V11.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V9.Types.TeamCreated p0 p1 p2 ->
            Evergreen.V11.Types.TeamCreated (p0 |> migrate_Types_Team) p1 p2

        Evergreen.V9.Types.TeamLoaded p0 p1 p2 p3 p4 ->
            Evergreen.V11.Types.TeamLoaded (p0 |> migrate_Types_Team)
                (p1 |> List.map migrate_Types_Match)
                p2
                (p3 |> List.map migrate_Types_AvailabilityRecord)
                (p4 |> Dict.map (\k -> Dict.map (\l -> Dict.map (\m -> migrate_Types_DatePrediction))))
                Dict.empty

        Evergreen.V9.Types.TeamNotFound ->
            Evergreen.V11.Types.TeamNotFound

        Evergreen.V9.Types.AccessCodeRequired p0 ->
            Evergreen.V11.Types.AccessCodeRequired p0

        Evergreen.V9.Types.MatchCreated p0 ->
            Evergreen.V11.Types.MatchCreated (p0 |> migrate_Types_Match)

        Evergreen.V9.Types.MemberCreated p0 ->
            Evergreen.V11.Types.MemberCreated (p0 |> migrate_Types_Member)

        Evergreen.V9.Types.AvailabilityUpdated p0 ->
            Evergreen.V11.Types.AvailabilityUpdated (p0 |> migrate_Types_AvailabilityRecord)

        Evergreen.V9.Types.MatchDateChanged p0 p1 ->
            Evergreen.V11.Types.MatchDateChanged p0 p1

        Evergreen.V9.Types.DatePredictionAdded p0 p1 ->
            Evergreen.V11.Types.DatePredictionAdded (p0 |> migrate_Types_DatePrediction) p1

        Evergreen.V9.Types.DatePredictionUpdated p0 p1 ->
            Evergreen.V11.Types.DatePredictionUpdated (p0 |> migrate_Types_DatePrediction) p1

        Evergreen.V9.Types.DatePredictionRemoved p0 p1 ->
            Evergreen.V11.Types.DatePredictionRemoved p0 p1

        Evergreen.V9.Types.PredictionsCleared p0 ->
            Evergreen.V11.Types.PredictionsCleared p0

        Evergreen.V9.Types.MatchOriginalDateSet p0 p1 ->
            Evergreen.V11.Types.MatchOriginalDateSet p0 p1

        Evergreen.V9.Types.NoOpToFrontend ->
            Evergreen.V11.Types.NoOpToFrontend
