module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V3.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , currentTeam = old.currentTeam
    , activeMemberId = old.activeMemberId
    , createTeamForm = old.createTeamForm |> migrate_Types_CreateTeamForm
    , createMatchForm = old.createMatchForm |> migrate_Types_CreateMatchForm
    , createMemberForm = old.createMemberForm |> migrate_Types_CreateMemberForm
    , matches = old.matches |> List.map migrate_Types_Match
    , members = old.members
    , availability = old.availability |> List.map migrate_Types_AvailabilityRecord
    , showCreateMatchModal = old.showCreateMatchModal
    , showCreateMemberModal = old.showCreateMemberModal
    , showMemberSelectionModal = old.showMemberSelectionModal
    , showCreateMemberInModal = False
    , showChangeMatchDateModal = False
    , changeMatchDateForm = ""
    , changeMatchDateMatchId = Nothing
    , expandedMatches = old.expandedMatches
    , pastMatchesShown = 0
    , pastMatchesExpanded = False
    , hostname = old.hostname
    }


migrate_Types_Availability : Evergreen.V1.Types.Availability -> Evergreen.V3.Types.Availability
migrate_Types_Availability old =
    case old of
        Evergreen.V1.Types.Available ->
            Evergreen.V3.Types.Available

        Evergreen.V1.Types.NotAvailable ->
            Evergreen.V3.Types.NotAvailable

        Evergreen.V1.Types.Maybe ->
            Evergreen.V3.Types.Maybe


migrate_Types_AvailabilityRecord : Evergreen.V1.Types.AvailabilityRecord -> Evergreen.V3.Types.AvailabilityRecord
migrate_Types_AvailabilityRecord old =
    { memberId = old.memberId
    , matchId = old.matchId
    , availability = old.availability |> migrate_Types_Availability
    }


migrate_Types_CreateMatchForm : Evergreen.V1.Types.CreateMatchForm -> Evergreen.V3.Types.CreateMatchForm
migrate_Types_CreateMatchForm old =
    old


migrate_Types_CreateMemberForm : Evergreen.V1.Types.CreateMemberForm -> Evergreen.V3.Types.CreateMemberForm
migrate_Types_CreateMemberForm old =
    old


migrate_Types_CreateTeamForm : Evergreen.V1.Types.CreateTeamForm -> Evergreen.V3.Types.CreateTeamForm
migrate_Types_CreateTeamForm old =
    old


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V3.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V3.Types.UrlChanged p0

        Evergreen.V1.Types.CreateTeamFormUpdated p0 ->
            Evergreen.V3.Types.CreateTeamFormUpdated (p0 |> migrate_Types_CreateTeamForm)

        Evergreen.V1.Types.CreateTeamSubmitted ->
            Evergreen.V3.Types.CreateTeamSubmitted

        Evergreen.V1.Types.CreateMatchFormUpdated p0 ->
            Evergreen.V3.Types.CreateMatchFormUpdated (p0 |> migrate_Types_CreateMatchForm)

        Evergreen.V1.Types.CreateMatchSubmitted p0 ->
            Evergreen.V3.Types.CreateMatchSubmitted p0

        Evergreen.V1.Types.ShowCreateMatchModal ->
            Evergreen.V3.Types.ShowCreateMatchModal

        Evergreen.V1.Types.HideCreateMatchModal ->
            Evergreen.V3.Types.HideCreateMatchModal

        Evergreen.V1.Types.CreateMemberFormUpdated p0 ->
            Evergreen.V3.Types.CreateMemberFormUpdated (p0 |> migrate_Types_CreateMemberForm)

        Evergreen.V1.Types.CreateMemberSubmitted p0 ->
            Evergreen.V3.Types.CreateMemberSubmitted p0

        Evergreen.V1.Types.ShowCreateMemberModal ->
            Evergreen.V3.Types.ShowCreateMemberModal

        Evergreen.V1.Types.HideCreateMemberModal ->
            Evergreen.V3.Types.HideCreateMemberModal

        Evergreen.V1.Types.ShowMemberSelectionModal ->
            Evergreen.V3.Types.ShowMemberSelectionModal

        Evergreen.V1.Types.HideMemberSelectionModal ->
            Evergreen.V3.Types.HideMemberSelectionModal

        Evergreen.V1.Types.SelectActiveMember p0 ->
            Evergreen.V3.Types.SelectActiveMember p0

        Evergreen.V1.Types.LocalStorageMessage p0 ->
            Evergreen.V3.Types.LocalStorageMessage p0

        Evergreen.V1.Types.LogoutRequested ->
            Evergreen.V3.Types.LogoutRequested

        Evergreen.V1.Types.SetAvailability p0 p1 p2 ->
            Evergreen.V3.Types.SetAvailability p0 p1 (p2 |> migrate_Types_Availability)

        Evergreen.V1.Types.ToggleMatchDetails p0 ->
            Evergreen.V3.Types.ToggleMatchDetails p0

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V3.Types.NoOpFrontendMsg


migrate_Types_Match : Evergreen.V1.Types.Match -> Evergreen.V3.Types.Match
migrate_Types_Match old =
    { id = old.id
    , opponent = old.opponent
    , date = old.date
    , time = old.time
    , isHome = old.isHome
    , venue = old.venue
    , season = old.season
    , seasonHalf = old.seasonHalf |> migrate_Types_SeasonHalf
    , matchday = old.matchday
    }


migrate_Types_Member : Evergreen.V1.Types.Member -> Evergreen.V3.Types.Member
migrate_Types_Member old =
    old


migrate_Types_Page : Evergreen.V1.Types.Page -> Evergreen.V3.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V1.Types.HomePage ->
            Evergreen.V3.Types.HomePage

        Evergreen.V1.Types.CreateTeamPage ->
            Evergreen.V3.Types.CreateTeamPage

        Evergreen.V1.Types.TeamPage p0 ->
            Evergreen.V3.Types.TeamPage p0

        Evergreen.V1.Types.NotFoundPage ->
            Evergreen.V3.Types.NotFoundPage


migrate_Types_SeasonHalf : Evergreen.V1.Types.SeasonHalf -> Evergreen.V3.Types.SeasonHalf
migrate_Types_SeasonHalf old =
    case old of
        Evergreen.V1.Types.Hinrunde ->
            Evergreen.V3.Types.Hinrunde

        Evergreen.V1.Types.Rückrunde ->
            Evergreen.V3.Types.Rückrunde


migrate_Types_Team : Evergreen.V1.Types.Team -> Evergreen.V3.Types.Team
migrate_Types_Team old =
    old


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V3.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.CreateTeamRequest p0 p1 p2 p3 ->
            Evergreen.V3.Types.CreateTeamRequest p0 p1 p2 p3

        Evergreen.V1.Types.GetTeamRequest p0 ->
            Evergreen.V3.Types.GetTeamRequest p0

        Evergreen.V1.Types.CreateMatchRequest p0 p1 ->
            Evergreen.V3.Types.CreateMatchRequest p0 (p1 |> migrate_Types_CreateMatchForm)

        Evergreen.V1.Types.CreateMemberRequest p0 p1 ->
            Evergreen.V3.Types.CreateMemberRequest p0 (p1 |> migrate_Types_CreateMemberForm)

        Evergreen.V1.Types.UpdateAvailabilityRequest p0 p1 p2 ->
            Evergreen.V3.Types.UpdateAvailabilityRequest p0 p1 (p2 |> migrate_Types_Availability)

        Evergreen.V1.Types.NoOpToBackend ->
            Evergreen.V3.Types.NoOpToBackend


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V3.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.TeamCreated p0 p1 ->
            Evergreen.V3.Types.TeamCreated (p0 |> migrate_Types_Team) p1

        Evergreen.V1.Types.TeamLoaded p0 p1 p2 p3 ->
            Evergreen.V3.Types.TeamLoaded (p0 |> migrate_Types_Team)
                (p1 |> List.map migrate_Types_Match)
                p2
                (p3 |> List.map migrate_Types_AvailabilityRecord)

        Evergreen.V1.Types.TeamNotFound ->
            Evergreen.V3.Types.TeamNotFound

        Evergreen.V1.Types.MatchCreated p0 ->
            Evergreen.V3.Types.MatchCreated (p0 |> migrate_Types_Match)

        Evergreen.V1.Types.MemberCreated p0 ->
            Evergreen.V3.Types.MemberCreated (p0 |> migrate_Types_Member)

        Evergreen.V1.Types.AvailabilityUpdated p0 ->
            Evergreen.V3.Types.AvailabilityUpdated (p0 |> migrate_Types_AvailabilityRecord)

        Evergreen.V1.Types.NoOpToFrontend ->
            Evergreen.V3.Types.NoOpToFrontend
