module Evergreen.Migrate.V7 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V6.Types
import Evergreen.V7.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V6.Types.FrontendModel -> ModelMigration Evergreen.V7.Types.FrontendModel Evergreen.V7.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V6.Types.BackendModel -> ModelMigration Evergreen.V7.Types.BackendModel Evergreen.V7.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V6.Types.FrontendMsg -> MsgMigration Evergreen.V7.Types.FrontendMsg Evergreen.V7.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V6.Types.ToBackend -> MsgMigration Evergreen.V7.Types.ToBackend Evergreen.V7.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V6.Types.BackendMsg -> MsgMigration Evergreen.V7.Types.BackendMsg Evergreen.V7.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V6.Types.ToFrontend -> MsgMigration Evergreen.V7.Types.ToFrontend Evergreen.V7.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V6.Types.FrontendModel -> Evergreen.V7.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = old.page |> migrate_Types_Page
    , currentTeam = old.currentTeam
    , activeMemberId = old.activeMemberId
    , createTeamForm = old.createTeamForm |> migrate_Types_CreateTeamForm
    , createMatchForm = old.createMatchForm |> migrate_Types_CreateMatchForm
    , createMemberForm = old.createMemberForm |> migrate_Types_CreateMemberForm
    , matches = old.matches |> List.map migrate_Types_Match
    , members = old.members
    , availability = old.availability |> List.map migrate_Types_AvailabilityRecord
    , showCreateMatchModal = old.showCreateMatchModal
    , showCreateMemberModal = old.showCreateMemberModal
    , showMemberSelectionModal = old.showMemberSelectionModal
    , showCreateMemberInModal = old.showCreateMemberInModal
    , showChangeMatchDateModal = old.showChangeMatchDateModal
    , changeMatchDateForm = old.changeMatchDateForm
    , changeMatchDateMatchId = old.changeMatchDateMatchId
    , showShareModal = old.showShareModal
    , expandedMatches = old.expandedMatches
    , pastMatchesShown = old.pastMatchesShown
    , pastMatchesExpanded = old.pastMatchesExpanded
    , hostname = old.hostname
    , currentDate = Nothing
    , confirmedTeamCodes = old.confirmedTeamCodes
    , accessCodeRequired = old.accessCodeRequired
    , enteredAccessCode = old.enteredAccessCode
    }


migrate_Types_Availability : Evergreen.V6.Types.Availability -> Evergreen.V7.Types.Availability
migrate_Types_Availability old =
    case old of
        Evergreen.V6.Types.Available ->
            Evergreen.V7.Types.Available

        Evergreen.V6.Types.NotAvailable ->
            Evergreen.V7.Types.NotAvailable

        Evergreen.V6.Types.Maybe ->
            Evergreen.V7.Types.Maybe


migrate_Types_AvailabilityRecord : Evergreen.V6.Types.AvailabilityRecord -> Evergreen.V7.Types.AvailabilityRecord
migrate_Types_AvailabilityRecord old =
    { memberId = old.memberId
    , matchId = old.matchId
    , availability = old.availability |> migrate_Types_Availability
    }


migrate_Types_CreateMatchForm : Evergreen.V6.Types.CreateMatchForm -> Evergreen.V7.Types.CreateMatchForm
migrate_Types_CreateMatchForm old =
    old


migrate_Types_CreateMemberForm : Evergreen.V6.Types.CreateMemberForm -> Evergreen.V7.Types.CreateMemberForm
migrate_Types_CreateMemberForm old =
    old


migrate_Types_CreateTeamForm : Evergreen.V6.Types.CreateTeamForm -> Evergreen.V7.Types.CreateTeamForm
migrate_Types_CreateTeamForm old =
    old


migrate_Types_FrontendMsg : Evergreen.V6.Types.FrontendMsg -> Evergreen.V7.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V6.Types.UrlClicked p0 ->
            Evergreen.V7.Types.UrlClicked p0

        Evergreen.V6.Types.UrlChanged p0 ->
            Evergreen.V7.Types.UrlChanged p0

        Evergreen.V6.Types.CreateTeamFormUpdated p0 ->
            Evergreen.V7.Types.CreateTeamFormUpdated (p0 |> migrate_Types_CreateTeamForm)

        Evergreen.V6.Types.CreateTeamSubmitted ->
            Evergreen.V7.Types.CreateTeamSubmitted

        Evergreen.V6.Types.CreateMatchFormUpdated p0 ->
            Evergreen.V7.Types.CreateMatchFormUpdated (p0 |> migrate_Types_CreateMatchForm)

        Evergreen.V6.Types.CreateMatchSubmitted p0 ->
            Evergreen.V7.Types.CreateMatchSubmitted p0

        Evergreen.V6.Types.ShowCreateMatchModal ->
            Evergreen.V7.Types.ShowCreateMatchModal

        Evergreen.V6.Types.HideCreateMatchModal ->
            Evergreen.V7.Types.HideCreateMatchModal

        Evergreen.V6.Types.CreateMemberFormUpdated p0 ->
            Evergreen.V7.Types.CreateMemberFormUpdated (p0 |> migrate_Types_CreateMemberForm)

        Evergreen.V6.Types.CreateMemberSubmitted p0 ->
            Evergreen.V7.Types.CreateMemberSubmitted p0

        Evergreen.V6.Types.ShowCreateMemberModal ->
            Evergreen.V7.Types.ShowCreateMemberModal

        Evergreen.V6.Types.HideCreateMemberModal ->
            Evergreen.V7.Types.HideCreateMemberModal

        Evergreen.V6.Types.ShowMemberSelectionModal ->
            Evergreen.V7.Types.ShowMemberSelectionModal

        Evergreen.V6.Types.HideMemberSelectionModal ->
            Evergreen.V7.Types.HideMemberSelectionModal

        Evergreen.V6.Types.SelectActiveMember p0 ->
            Evergreen.V7.Types.SelectActiveMember p0

        Evergreen.V6.Types.ShowCreateMemberInModal ->
            Evergreen.V7.Types.ShowCreateMemberInModal

        Evergreen.V6.Types.HideCreateMemberInModal ->
            Evergreen.V7.Types.HideCreateMemberInModal

        Evergreen.V6.Types.LocalStorageMessage p0 ->
            Evergreen.V7.Types.LocalStorageMessage p0

        Evergreen.V6.Types.LogoutRequested ->
            Evergreen.V7.Types.LogoutRequested

        Evergreen.V6.Types.SetAvailability p0 p1 p2 ->
            Evergreen.V7.Types.SetAvailability p0 p1 (p2 |> migrate_Types_Availability)

        Evergreen.V6.Types.ToggleMatchDetails p0 ->
            Evergreen.V7.Types.ToggleMatchDetails p0

        Evergreen.V6.Types.LoadMorePastMatches ->
            Evergreen.V7.Types.LoadMorePastMatches

        Evergreen.V6.Types.TogglePastMatchesSection ->
            Evergreen.V7.Types.TogglePastMatchesSection

        Evergreen.V6.Types.ShowChangeMatchDateModal p0 ->
            Evergreen.V7.Types.ShowChangeMatchDateModal p0

        Evergreen.V6.Types.HideChangeMatchDateModal ->
            Evergreen.V7.Types.HideChangeMatchDateModal

        Evergreen.V6.Types.ChangeMatchDateFormUpdated p0 p1 ->
            Evergreen.V7.Types.ChangeMatchDateFormUpdated p0 p1

        Evergreen.V6.Types.ChangeMatchDateSubmitted p0 p1 ->
            Evergreen.V7.Types.ChangeMatchDateSubmitted p0 p1

        Evergreen.V6.Types.ShowShareModal ->
            Evergreen.V7.Types.ShowShareModal

        Evergreen.V6.Types.HideShareModal ->
            Evergreen.V7.Types.HideShareModal

        Evergreen.V6.Types.SubmitAccessCodeRequested p0 p1 ->
            Evergreen.V7.Types.SubmitAccessCodeRequested p0 p1

        Evergreen.V6.Types.AccessCodeInputChanged p0 p1 ->
            Evergreen.V7.Types.AccessCodeInputChanged p0 p1

        Evergreen.V6.Types.GetAccessCode p0 ->
            Evergreen.V7.Types.GetAccessCode p0

        Evergreen.V6.Types.AccessCodeLoaded p0 p1 ->
            Evergreen.V7.Types.AccessCodeLoaded p0 p1

        Evergreen.V6.Types.CopyToClipboard p0 ->
            Evergreen.V7.Types.CopyToClipboard p0

        Evergreen.V6.Types.NoOpFrontendMsg ->
            Evergreen.V7.Types.NoOpFrontendMsg


migrate_Types_Match : Evergreen.V6.Types.Match -> Evergreen.V7.Types.Match
migrate_Types_Match old =
    { id = old.id
    , opponent = old.opponent
    , date = old.date
    , time = old.time
    , isHome = old.isHome
    , venue = old.venue
    , season = old.season
    , seasonHalf = old.seasonHalf |> migrate_Types_SeasonHalf
    , matchday = old.matchday
    }


migrate_Types_Page : Evergreen.V6.Types.Page -> Evergreen.V7.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V6.Types.HomePage ->
            Evergreen.V7.Types.HomePage

        Evergreen.V6.Types.CreateTeamPage ->
            Evergreen.V7.Types.CreateTeamPage

        Evergreen.V6.Types.TeamPage p0 ->
            Evergreen.V7.Types.TeamPage p0

        Evergreen.V6.Types.NotFoundPage ->
            Evergreen.V7.Types.NotFoundPage


migrate_Types_SeasonHalf : Evergreen.V6.Types.SeasonHalf -> Evergreen.V7.Types.SeasonHalf
migrate_Types_SeasonHalf old =
    case old of
        Evergreen.V6.Types.Hinrunde ->
            Evergreen.V7.Types.Hinrunde

        Evergreen.V6.Types.Rückrunde ->
            Evergreen.V7.Types.Rückrunde
